// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/qsydev/goterm/pkg/idk/proto/executors.proto

package idk // import "github.com/qsydev/goterm/pkg/idk"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Color int32

const (
	Color_RED     Color = 0
	Color_GREEN   Color = 1
	Color_BLUE    Color = 2
	Color_MAGENTA Color = 3
	Color_CYAN    Color = 4
	Color_YELLOW  Color = 5
	Color_WHITE   Color = 6
)

var Color_name = map[int32]string{
	0: "RED",
	1: "GREEN",
	2: "BLUE",
	3: "MAGENTA",
	4: "CYAN",
	5: "YELLOW",
	6: "WHITE",
}
var Color_value = map[string]int32{
	"RED":     0,
	"GREEN":   1,
	"BLUE":    2,
	"MAGENTA": 3,
	"CYAN":    4,
	"YELLOW":  5,
	"WHITE":   6,
}

func (x Color) String() string {
	return proto.EnumName(Color_name, int32(x))
}
func (Color) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_executors_cb968aada9a389f3, []int{0}
}

type PlayerExecutor struct {
	Colors               []Color  `protobuf:"varint,1,rep,packed,name=colors,proto3,enum=idk.Color" json:"colors,omitempty"`
	Timeout              int64    `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Delay                int64    `protobuf:"varint,3,opt,name=delay,proto3" json:"delay,omitempty"`
	Duration             int64    `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Steps                int32    `protobuf:"varint,5,opt,name=steps,proto3" json:"steps,omitempty"`
	StopOnTimeout        bool     `protobuf:"varint,6,opt,name=stopOnTimeout,proto3" json:"stopOnTimeout,omitempty"`
	WaitForAllPlayers    bool     `protobuf:"varint,7,opt,name=waitForAllPlayers,proto3" json:"waitForAllPlayers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerExecutor) Reset()         { *m = PlayerExecutor{} }
func (m *PlayerExecutor) String() string { return proto.CompactTextString(m) }
func (*PlayerExecutor) ProtoMessage()    {}
func (*PlayerExecutor) Descriptor() ([]byte, []int) {
	return fileDescriptor_executors_cb968aada9a389f3, []int{0}
}
func (m *PlayerExecutor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerExecutor.Unmarshal(m, b)
}
func (m *PlayerExecutor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerExecutor.Marshal(b, m, deterministic)
}
func (dst *PlayerExecutor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerExecutor.Merge(dst, src)
}
func (m *PlayerExecutor) XXX_Size() int {
	return xxx_messageInfo_PlayerExecutor.Size(m)
}
func (m *PlayerExecutor) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerExecutor.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerExecutor proto.InternalMessageInfo

func (m *PlayerExecutor) GetColors() []Color {
	if m != nil {
		return m.Colors
	}
	return nil
}

func (m *PlayerExecutor) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *PlayerExecutor) GetDelay() int64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *PlayerExecutor) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *PlayerExecutor) GetSteps() int32 {
	if m != nil {
		return m.Steps
	}
	return 0
}

func (m *PlayerExecutor) GetStopOnTimeout() bool {
	if m != nil {
		return m.StopOnTimeout
	}
	return false
}

func (m *PlayerExecutor) GetWaitForAllPlayers() bool {
	if m != nil {
		return m.WaitForAllPlayers
	}
	return false
}

type CustomExecutor struct {
	Duration             int64                  `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Steps                []*CustomExecutor_Step `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CustomExecutor) Reset()         { *m = CustomExecutor{} }
func (m *CustomExecutor) String() string { return proto.CompactTextString(m) }
func (*CustomExecutor) ProtoMessage()    {}
func (*CustomExecutor) Descriptor() ([]byte, []int) {
	return fileDescriptor_executors_cb968aada9a389f3, []int{1}
}
func (m *CustomExecutor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomExecutor.Unmarshal(m, b)
}
func (m *CustomExecutor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomExecutor.Marshal(b, m, deterministic)
}
func (dst *CustomExecutor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomExecutor.Merge(dst, src)
}
func (m *CustomExecutor) XXX_Size() int {
	return xxx_messageInfo_CustomExecutor.Size(m)
}
func (m *CustomExecutor) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomExecutor.DiscardUnknown(m)
}

var xxx_messageInfo_CustomExecutor proto.InternalMessageInfo

func (m *CustomExecutor) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *CustomExecutor) GetSteps() []*CustomExecutor_Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

type CustomExecutor_Step struct {
	NodeConfigs          []*CustomExecutor_Step_NodeConfig `protobuf:"bytes,1,rep,name=nodeConfigs,proto3" json:"nodeConfigs,omitempty"`
	Timeout              int64                             `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Expression           string                            `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`
	StopOnTimeout        bool                              `protobuf:"varint,4,opt,name=stopOnTimeout,proto3" json:"stopOnTimeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CustomExecutor_Step) Reset()         { *m = CustomExecutor_Step{} }
func (m *CustomExecutor_Step) String() string { return proto.CompactTextString(m) }
func (*CustomExecutor_Step) ProtoMessage()    {}
func (*CustomExecutor_Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_executors_cb968aada9a389f3, []int{1, 0}
}
func (m *CustomExecutor_Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomExecutor_Step.Unmarshal(m, b)
}
func (m *CustomExecutor_Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomExecutor_Step.Marshal(b, m, deterministic)
}
func (dst *CustomExecutor_Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomExecutor_Step.Merge(dst, src)
}
func (m *CustomExecutor_Step) XXX_Size() int {
	return xxx_messageInfo_CustomExecutor_Step.Size(m)
}
func (m *CustomExecutor_Step) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomExecutor_Step.DiscardUnknown(m)
}

var xxx_messageInfo_CustomExecutor_Step proto.InternalMessageInfo

func (m *CustomExecutor_Step) GetNodeConfigs() []*CustomExecutor_Step_NodeConfig {
	if m != nil {
		return m.NodeConfigs
	}
	return nil
}

func (m *CustomExecutor_Step) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *CustomExecutor_Step) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

func (m *CustomExecutor_Step) GetStopOnTimeout() bool {
	if m != nil {
		return m.StopOnTimeout
	}
	return false
}

type CustomExecutor_Step_NodeConfig struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Delay                int64    `protobuf:"varint,2,opt,name=delay,proto3" json:"delay,omitempty"`
	Color                Color    `protobuf:"varint,3,opt,name=color,proto3,enum=idk.Color" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomExecutor_Step_NodeConfig) Reset()         { *m = CustomExecutor_Step_NodeConfig{} }
func (m *CustomExecutor_Step_NodeConfig) String() string { return proto.CompactTextString(m) }
func (*CustomExecutor_Step_NodeConfig) ProtoMessage()    {}
func (*CustomExecutor_Step_NodeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_executors_cb968aada9a389f3, []int{1, 0, 0}
}
func (m *CustomExecutor_Step_NodeConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomExecutor_Step_NodeConfig.Unmarshal(m, b)
}
func (m *CustomExecutor_Step_NodeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomExecutor_Step_NodeConfig.Marshal(b, m, deterministic)
}
func (dst *CustomExecutor_Step_NodeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomExecutor_Step_NodeConfig.Merge(dst, src)
}
func (m *CustomExecutor_Step_NodeConfig) XXX_Size() int {
	return xxx_messageInfo_CustomExecutor_Step_NodeConfig.Size(m)
}
func (m *CustomExecutor_Step_NodeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomExecutor_Step_NodeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CustomExecutor_Step_NodeConfig proto.InternalMessageInfo

func (m *CustomExecutor_Step_NodeConfig) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomExecutor_Step_NodeConfig) GetDelay() int64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *CustomExecutor_Step_NodeConfig) GetColor() Color {
	if m != nil {
		return m.Color
	}
	return Color_RED
}

func init() {
	proto.RegisterType((*PlayerExecutor)(nil), "idk.PlayerExecutor")
	proto.RegisterType((*CustomExecutor)(nil), "idk.CustomExecutor")
	proto.RegisterType((*CustomExecutor_Step)(nil), "idk.CustomExecutor.Step")
	proto.RegisterType((*CustomExecutor_Step_NodeConfig)(nil), "idk.CustomExecutor.Step.NodeConfig")
	proto.RegisterEnum("idk.Color", Color_name, Color_value)
}

func init() {
	proto.RegisterFile("github.com/qsydev/goterm/pkg/idk/proto/executors.proto", fileDescriptor_executors_cb968aada9a389f3)
}

var fileDescriptor_executors_cb968aada9a389f3 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x6f, 0x13, 0x31,
	0x14, 0x64, 0x3f, 0xbc, 0x49, 0x5f, 0x44, 0xb4, 0x58, 0x1c, 0xac, 0x1c, 0xd0, 0x2a, 0x70, 0x58,
	0x21, 0xb4, 0x2b, 0x05, 0x89, 0x7b, 0x1a, 0x4c, 0x41, 0x0a, 0x29, 0x72, 0x83, 0xaa, 0x72, 0x4b,
	0x63, 0x13, 0xac, 0x6c, 0xe2, 0xc5, 0xf6, 0x42, 0x73, 0xe6, 0x9f, 0x72, 0xe4, 0x57, 0xa0, 0xf5,
	0xa6, 0x69, 0x42, 0x80, 0x1e, 0x67, 0xc6, 0xa3, 0x37, 0x9e, 0xf7, 0xe0, 0xd5, 0x42, 0xda, 0x2f,
	0xd5, 0x75, 0x36, 0x57, 0xab, 0xfc, 0xab, 0xd9, 0x70, 0xf1, 0x2d, 0x5f, 0x28, 0x2b, 0xf4, 0x2a,
	0x2f, 0x97, 0x8b, 0x5c, 0xf2, 0x65, 0x5e, 0x6a, 0x65, 0x55, 0x2e, 0x6e, 0xc4, 0xbc, 0xb2, 0x4a,
	0x9b, 0xcc, 0x61, 0x1c, 0x48, 0xbe, 0xec, 0xff, 0xf2, 0xa0, 0xfb, 0xa1, 0x98, 0x6d, 0x84, 0xa6,
	0x5b, 0x19, 0xf7, 0x21, 0x9a, 0xab, 0x42, 0x69, 0x43, 0xbc, 0x24, 0x48, 0xbb, 0x03, 0xc8, 0x24,
	0x5f, 0x66, 0xa3, 0x9a, 0x62, 0x5b, 0x05, 0x13, 0x68, 0x59, 0xb9, 0x12, 0xaa, 0xb2, 0xc4, 0x4f,
	0xbc, 0x34, 0x60, 0xb7, 0x10, 0x3f, 0x06, 0xc4, 0x45, 0x31, 0xdb, 0x90, 0xc0, 0xf1, 0x0d, 0xc0,
	0x3d, 0x68, 0xf3, 0x4a, 0xcf, 0xac, 0x54, 0x6b, 0x12, 0x3a, 0x61, 0x87, 0x6b, 0x87, 0xb1, 0xa2,
	0x34, 0x04, 0x25, 0x5e, 0x8a, 0x58, 0x03, 0xf0, 0x33, 0x78, 0x68, 0xac, 0x2a, 0xcf, 0xd7, 0xd3,
	0xed, 0x9c, 0x28, 0xf1, 0xd2, 0x36, 0x3b, 0x24, 0xf1, 0x0b, 0x78, 0xf4, 0x7d, 0x26, 0xed, 0x1b,
	0xa5, 0x87, 0x45, 0xd1, 0xfc, 0xc3, 0x90, 0x96, 0x7b, 0x79, 0x2c, 0xf4, 0x7f, 0xfa, 0xd0, 0x1d,
	0x55, 0xc6, 0xaa, 0xd5, 0xee, 0xb3, 0xfb, 0xc1, 0xbc, 0x3f, 0x82, 0x65, 0xb7, 0xc1, 0xfc, 0x24,
	0x48, 0x3b, 0x03, 0xd2, 0xf4, 0x70, 0xe0, 0xcf, 0x2e, 0xac, 0x28, 0xb7, 0x91, 0x7b, 0x3f, 0x7c,
	0x08, 0x6b, 0x8c, 0x29, 0x74, 0xd6, 0x8a, 0x8b, 0x91, 0x5a, 0x7f, 0x96, 0x8b, 0xa6, 0xc6, 0xce,
	0xe0, 0xe9, 0xbf, 0xec, 0xd9, 0x64, 0xf7, 0x96, 0xed, 0xfb, 0xfe, 0x53, 0xf2, 0x13, 0x00, 0x71,
	0x53, 0x6a, 0x61, 0x4c, 0x9d, 0xbb, 0x6e, 0xfa, 0x84, 0xed, 0x31, 0xc7, 0xe5, 0x85, 0x7f, 0x29,
	0xaf, 0x37, 0x05, 0xb8, 0x1b, 0x8d, 0xbb, 0xe0, 0x4b, 0xee, 0x3a, 0x40, 0xcc, 0x97, 0xfc, 0x6e,
	0x91, 0xfe, 0xfe, 0x22, 0x13, 0x40, 0xee, 0x04, 0xdc, 0xd0, 0xc3, 0xdb, 0x68, 0x84, 0xe7, 0x17,
	0x80, 0x1c, 0xc6, 0x2d, 0x08, 0x18, 0x7d, 0x1d, 0x3f, 0xc0, 0x27, 0x80, 0xce, 0x18, 0xa5, 0x93,
	0xd8, 0xc3, 0x6d, 0x08, 0x4f, 0xc7, 0x1f, 0x69, 0xec, 0xe3, 0x0e, 0xb4, 0xde, 0x0f, 0xcf, 0xe8,
	0x64, 0x3a, 0x8c, 0x83, 0x9a, 0x1e, 0x5d, 0x0d, 0x27, 0x71, 0x88, 0x01, 0xa2, 0x2b, 0x3a, 0x1e,
	0x9f, 0x5f, 0xc6, 0xa8, 0xf6, 0x5d, 0xbe, 0x7d, 0x37, 0xa5, 0x71, 0x74, 0xda, 0xff, 0x94, 0xdc,
	0x77, 0xe5, 0xd7, 0x91, 0x3b, 0xeb, 0x97, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x7e, 0x47,
	0x17, 0x10, 0x03, 0x00, 0x00,
}
